name: traveltranslation
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.1+2

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  share: ^0.6.1+1
  event_bus: ^1.1.0
  camera: ^0.5.4+1
  permission_handler: ^3.2.0
  flutter_slidable: ^0.5.4
  cupertino_icons: ^0.1.2
  bloc: ^0.14.0
  flutter_bloc: ^0.18.0
  image_picker: ^0.6.0+5
  toast: ^0.1.3
  equatable: ^0.2.0
  ocr_plugin: ^0.0.6
  dio: 2.1.13  #latest version
  #  multi_image_picker: ^4.1.1
  multi_image_picker: ^4.5.3
  image_cropper: ^1.0.2
  crypto: ^2.0.6
  json_serializable: ^3.1.0
  path_provider: ^1.1.2
  video_player: ^0.10.1+5
  flutter_svg: ^0.13.1
  photo_view: ^0.4.2
  shimmer: ^1.0.0
  progress_dialog: ^1.2.0
  share_extend: ^1.0.9
  oktoast: ^2.2.0
  flutter_screenutil: ^0.5.3
  cached_network_image: ^1.1.1
  #  extended_image: ^0.5.4
  flutter_image_compress: ^0.6.3
  device_id: ^0.2.0
  device_info: ^0.4.0+2
  package_info: ^0.4.0+2
  shared_preferences: ^0.5.3+4
  sqflite: ^1.1.6
  fluro: ^1.5.1
  fluwx: ^1.0.4
  tobias: ^1.1.0+1
  flutter_ads: '0.1.1'
  nova_utils: ^0.0.3
  flutter_localizations:
    sdk: flutter
  umeng_plugin: ^0.0.2
  webview_flutter: ^0.3.13
  rate_my_app: ^0.3.0+4
  auto_size_text: ^2.1.0
  in_app_purchase: ^0.2.1+3
  wave: ^0.0.8
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.6.1
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - images/
    - images/2.0x/
    - images/3.0x/
    - files/
#    - images/meizi.png
#    - images/icon_vip.png
#    - images/icon_vip2.png
#    - images/icon_help.png
#    - images/icon_advice.png
#    - images/icon_camera.png
#    - images/icon_history.png
#    - images/icon_setting.png
#    - images/icon_picture.png
#    - images/icon_crop.png
#    - images/icon_proofreading.png
#    - images/icon_copy_open.png
#    - images/icon_translation.png
#    - images/icon_backtohome.png
#    - images/icon_sharetext.png
#    - images/icon_delete_pic.png
#    - images/icon_qq.png
#    - images/icon_weixin.png
#    - images/icon_vip_banner.png
#    - images/icon_vip_month.png
#    - images/icon_vip_month_un.png
#    - images/icon_empty_history.png
#    - images/icon_wechat.png
#    - images/icon_zhifubao.png
#    - images/icon_vip_unselected.png
#    - images/icon_vip_select.png
#    - images/icon_vip_chip.png
#    - images/icon_toast_close.png
#    - images/icon_pic_login.png
#    - images/icon_login.png
#    - images/icon_unlogin.png
#    - images/pic_payment_successful.png
#    - images/icon_privacy.png
#    - images/translate_icon_cancel.png
#    - images/icon_share_weixin.png



  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
